title: Lauren Terschan
description: Personal blog

url: 'https://lofo10.github.io/'
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: '' # Ex: /project-page; leave blank as '' if using a custom domain
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Posts
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com
    linkedin: lauren-terschan

#google_analytics: "UA-58263416-1"

#disqus:
#    shortname: brianmaierjr
